#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE kisakes;
    CREATE DATABASE dummydb;

    GRANT ALL PRIVILEGES ON DATABASE kisakes TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE dummydb TO $POSTGRES_USER;
EOSQL
